#PRAGMA NAMESPACE ("\\\\.\\root\\subscription")
instance of CommandLineEventConsumer as $c1
{
    Name = "Kingsguard-1";
    RunInteractively=false;
    CommandLineTemplate="cmd.exe /c C:\\windows\\system32\\knight.exe C:\\windows\\system32\\kingsguard.dll Taskmgr.exe";
};
instance of __EventFilter as $f1
{
    Name = "Kingsguard-1";
    EventNamespace = "root\\cimv2";
    Query ="SELECT * FROM __InstanceCreationEvent Within 3 "
            "Where TargetInstance Isa \"Win32_Process\" "
            "And Targetinstance.Name LIKE \"Taskmgr.exe\" ";
    QueryLanguage = "WQL";
};
instance of __FilterToConsumerBinding
{
     Filter = $f1;
     Consumer = $c1;
};

instance of CommandLineEventConsumer as $c2
{
    Name = "Kingsguard-2";
    RunInteractively=false;
    CommandLineTemplate="cmd.exe /c C:\\windows\\system32\\knight.exe C:\\windows\\system32\\kingsguard.dll procexp.exe";
};
instance of __EventFilter as $f2
{
    Name = "Kingsguard-2";
    EventNamespace = "root\\cimv2";
    Query ="SELECT * FROM __InstanceCreationEvent Within 3 "
            "Where TargetInstance Isa \"Win32_Process\" "
            "And Targetinstance.Name LIKE \"procexp.exe\" ";
    QueryLanguage = "WQL";
};
instance of __FilterToConsumerBinding
{
     Filter = $f2;
     Consumer = $c2;
};

instance of CommandLineEventConsumer as $c3
{
    Name = "Kingsguard-3";
    RunInteractively=false;
    CommandLineTemplate="cmd.exe /c C:\\windows\\system32\\knight.exe C:\\windows\\system32\\kingsguard.dll procexp64.exe";
};
instance of __EventFilter as $f3
{
    Name = "Kingsguard-3";
    EventNamespace = "root\\cimv2";
    Query ="SELECT * FROM __InstanceCreationEvent Within 3 "
            "Where TargetInstance Isa \"Win32_Process\" "
            "And Targetinstance.Name LIKE \"procexp64.exe\" ";
    QueryLanguage = "WQL";
};
instance of __FilterToConsumerBinding
{
     Filter = $f3;
     Consumer = $c3;
};
